global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "user_api"
    static_configs:
      - targets: ["user-api:8000"]

  - job_name: "task_api"
    static_configs:
      - targets: ["task-api:8001"]
